import { addIcons } from 'ionicons';
import {
  addOutline,
  archiveOutline,
  arrowBackOutline,
  banOutline,
  calendarOutline,
  checkmarkCircleOutline,
  chevronBackOutline,
  chevronDownOutline,
  chevronForwardOutline,
  chevronUpOutline,
  closeCircleOutline,
  createOutline,
  flagOutline,
  listOutline,
  lockClosedOutline,
  openOutline,
  refreshOutline,
  timeOutline,
  trashOutline,
} from 'ionicons/icons';

export function registerAppIcons(): void {
  addIcons({
    addOutline,
    archiveOutline,
    arrowBackOutline,
    banOutline,
    calendarOutline,
    checkmarkCircleOutline,
    chevronBackOutline,
    chevronDownOutline,
    chevronForwardOutline,
    chevronUpOutline,
    closeCircleOutline,
    createOutline,
    flagOutline,
    listOutline,
    lockClosedOutline,
    openOutline,
    refreshOutline,
    timeOutline,
    trashOutline,
  });
}
